### ISSUE TITLE
compiling errr

### ISSUE THREAD

**Issue by starsx2016** [alessandromatera/what-tinys.it#1]
Arduino : 1.6.12 (Mac OS X), Carte : "Arduino Duemilanove or Diecimila, ATmega328"

/Users/starsx/Dropbox/project/what-tinys.it-master/firmware/WhatTinysIt_v_1/WhatTinysIt_v_1.ino: In function 'void setup()':
WhatTinysIt_v_1:49: error: 'button' was not declared in this scope
   pinMode(button, INPUT);
           ^
/Users/starsx/Dropbox/project/what-tinys.it-master/firmware/WhatTinysIt_v_1/WhatTinysIt_v_1.ino: In function 'void loop()':
WhatTinysIt_v_1:77: error: 'button' was not declared in this scope
     while(!digitalRead(button)){
                        ^
/Users/starsx/Dropbox/project/what-tinys.it-master/firmware/WhatTinysIt_v_1/WhatTinysIt_v_1.ino: In function 'void setClock()':
WhatTinysIt_v_1:156: error: 'button' was not declared in this scope
   while(!digitalRead(button)){
                      ^
WhatTinysIt_v_1:178: error: 'button' was not declared in this scope
     while(!digitalRead(button)){ 
                        ^
WhatTinysIt_v_1:199: error: 'button' was not declared in this scope
       while(!digitalRead(button)){
                          ^
WhatTinysIt_v_1:212: error: 'button' was not declared in this scope
     while(!digitalRead(button)){
                        ^
WhatTinysIt_v_1:231: error: 'button' was not declared in this scope
       while(!digitalRead(button)){
                          ^
exit status 1
'button' was not declared in this scope

**Comment by alessandromatera** [comment]
Try this:

At the top of the sketch, after define declarations, write:

Int button = A4;

Instead 
#define A4 button

**Comment by starsx2016** [comment]
thank you
